theme: jekyll-theme-cayman
title: Custom Captcha
description: Extending Google reCaptcha v3 with a custom checkbox creating a custom and unique one.
keywords: Custom, Customizable, Captcha, reCAPTCHA, Custom Captcha, Custom reCaptcha, Customizable Captcha, Customizable reCaptcha, Custom Google Captcha, reCaptcha custom logo, reCaptcha custom text, reCaptcha custom image
show_downloads: false
